# Dockerfile for ReactJS

# Use the official Node.js image.
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the project files
COPY . /app/

# Build the React application
RUN npm run build

# Serve the React application using a static server
RUN npm install -g serve
CMD ["serve", "-s", "build", "-l", "3000"]
