services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    ports:
      - "80:80"
      - "443:443"
      - "8081:81"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
